# Generated by Django 4.2.23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default="Mariam's Portfolio", help_text='Site title', max_length=200)),
                ('site_description', models.TextField(default='Frontend Developer Portfolio', help_text='Site description')),
                ('site_keywords', models.CharField(default='portfolio, frontend, developer, web design', help_text='SEO keywords', max_length=500)),
                ('email', models.EmailField(default='mariam@example.com', help_text='Contact email', max_length=254)),
                ('phone', models.CharField(default='+1 234 567 8900', help_text='Contact phone', max_length=20)),
                ('location', models.CharField(default='New York, NY', help_text='Location', max_length=100)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics ID', max_length=50)),
                ('meta_image', models.ImageField(blank=True, help_text='Meta image for social sharing', upload_to='meta/')),
                ('enable_blog', models.BooleanField(default=False, help_text='Enable blog section')),
                ('enable_contact_form', models.BooleanField(default=True, help_text='Enable contact form')),
                ('enable_dark_mode', models.BooleanField(default=True, help_text='Enable dark mode toggle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Theme', help_text='Theme name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is this theme currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_color', models.CharField(default='#667eea', help_text='Primary color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#764ba2', help_text='Secondary color (hex)', max_length=7)),
                ('accent_color', models.CharField(default='#f093fb', help_text='Accent color (hex)', max_length=7)),
                ('background_color', models.CharField(default='#1a1a2e', help_text='Background color (hex)', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', help_text='Text color (hex)', max_length=7)),
                ('card_color', models.CharField(default='#16213e', help_text='Card/box color (hex)', max_length=7)),
                ('font_family', models.CharField(default='Poppins', help_text='Main font family', max_length=100)),
                ('heading_font', models.CharField(default='Turret Road', help_text='Heading font family', max_length=100)),
                ('font_size_base', models.IntegerField(default=16, help_text='Base font size (px)')),
                ('sidebar_width', models.IntegerField(default=100, help_text='Sidebar width (px)')),
                ('border_radius', models.IntegerField(default=8, help_text='Border radius (px)')),
                ('spacing_unit', models.IntegerField(default=16, help_text='Spacing unit (px)')),
                ('enable_animations', models.BooleanField(default=True, help_text='Enable animations')),
                ('animation_speed', models.FloatField(default=1.0, help_text='Animation speed multiplier')),
                ('enable_stars', models.BooleanField(default=True, help_text='Enable star background')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS code')),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
