# Generated by Django 4.2.23 on 2025-09-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='Degree name', max_length=200)),
                ('institution', models.CharField(help_text='Institution name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details')),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(blank=True, help_text='End date', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Currently studying')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this education')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('description', models.TextField(help_text='Job description')),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if current)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Current job')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this experience')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('description', models.TextField(help_text='Project description')),
                ('image', models.ImageField(blank=True, help_text='Project image', upload_to='projects/')),
                ('technologies', models.CharField(help_text='Technologies used (comma separated)', max_length=500)),
                ('demo_url', models.URLField(blank=True, help_text='Demo URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub URL')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skill name', max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('tools', 'Tools'), ('other', 'Other')], default='frontend', help_text='Skill category', max_length=50)),
                ('proficiency', models.IntegerField(default=80, help_text='Proficiency percentage (0-100)')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_description',
            field=models.TextField(default='I am a passionate frontend developer with expertise in creating beautiful and functional web applications.', help_text='About section description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='About Me', help_text='About section title', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bio',
            field=models.TextField(default='I have high level experience in web design, development knowledge and producing quality work', help_text='Short bio/description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='full_name',
            field=models.CharField(default='Shazib', help_text='Your full name', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='job_title',
            field=models.CharField(default='Frontend Developer', help_text='Your job title', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Your profile image', upload_to='profile/'),
        ),
    ]
