# Generated by Django 5.2.6 on 2025-09-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_education_experience_project_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Section subtitle', max_length=300)),
                ('section_type', models.CharField(choices=[('services', 'Services'), ('testimonials', 'Testimonials'), ('stats', 'Statistics'), ('custom', 'Custom Content')], default='custom', help_text='Type of section', max_length=20)),
                ('content', models.TextField(help_text='Section content (supports HTML)')),
                ('icon_class', models.CharField(blank=True, help_text="CSS class for icon (e.g., 'uil uil-palette')", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Section',
                'verbose_name_plural': 'Landing Page Sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service title', max_length=200)),
                ('description', models.TextField(help_text='Service description')),
                ('icon_class', models.CharField(help_text="CSS class for icon (e.g., 'uil uil-web-grid')", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
