# Generated by Django 5.2.6 on 2025-09-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_landingpagesection_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='completed_projects',
            field=models.CharField(default='30+', help_text='Number of completed projects', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_text',
            field=models.CharField(default='More About me!', help_text='Call-to-action button text', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_image_url',
            field=models.URLField(blank=True, default='https://i.postimg.cc/3NgvPcZD/home-img.png', help_text='URL for the home section profile image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_follow_text',
            field=models.CharField(default='Follow Me', help_text='Text for social media section', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_availability',
            field=models.CharField(default='Online 24/7', help_text='Support availability text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='welcome_message',
            field=models.CharField(default="Hi, I'm", help_text="Welcome message prefix (e.g., 'Hi, I'm', 'Hello, I'm', 'Welcome, I'm')", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='years_experience',
            field=models.CharField(default='5+', help_text='Years of experience display', max_length=20),
        ),
    ]
