# Generated by Django 5.2.6 on 2025-09-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sitesettings_completed_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_display',
            field=models.CharField(blank=True, help_text='What to show for email contact (leave blank for email)', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='messenger_display',
            field=models.CharField(blank=True, help_text='What to show for Messenger contact (leave blank for full name)', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_display',
            field=models.CharField(blank=True, help_text='What to show for WhatsApp contact (leave blank for phone)', max_length=100),
        ),
    ]
