# Generated by Django 5.2.6 on 2025-09-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sitesettings_email_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='full_name',
            field=models.CharField(default='Shazib S', help_text='Your full name', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='welcome_message',
            field=models.CharField(default='Hello, I am', help_text="Welcome message prefix (e.g., 'Hi, I'm', 'Hello, I'm', 'Welcome, I'm')", max_length=200),
        ),
    ]
