# Generated by Django 5.2.6 on 2025-09-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sitesettings_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='welcome_message',
            field=models.CharField(default='Hello, I am', help_text="Welcome message prefix ONLY (e.g., 'Hello, I am', 'Hi, I'm', 'Welcome, I'm'). Do NOT include your name - it will be added automatically from the Full Name field.", max_length=200),
        ),
    ]
