# Generated by Django 5.2.6 on 2025-09-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_sitesettings_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Image for the about section', upload_to='profile/'),
        ),
    ]
