# Generated by Django 5.2.6 on 2025-09-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sitesettings_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_background_image',
            field=models.ImageField(blank=True, help_text='Background image for the home section', upload_to='backgrounds/'),
        ),
    ]
