# Generated by Django 5.2.6 on 2025-09-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sitesettings_home_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's name", max_length=100)),
                ('position', models.CharField(help_text="Client's job title or position", max_length=100)),
                ('company', models.CharField(blank=True, help_text="Client's company (optional)", max_length=100)),
                ('testimonial_text', models.TextField(help_text='The testimonial content')),
                ('image', models.ImageField(blank=True, help_text="Client's photo (optional)", null=True, upload_to='testimonials/')),
                ('date', models.DateField(help_text='Date when the testimonial was given')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Rating from 1 to 5 stars')),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial on the website')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'date'],
            },
        ),
    ]
