# Generated by Django 5.2.6 on 2025-09-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_subtitle',
            field=models.CharField(default='Contact me', help_text='Contact section subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_title',
            field=models.CharField(default='Get in Touch', help_text='Contact section title', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_about_image',
            field=models.URLField(blank=True, default='https://i.postimg.cc/2SXX3YbS/Screenshot-from-2025-08-28-19-27-55.png', help_text='Default image for about section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_project_image',
            field=models.URLField(blank=True, default='https://i.postimg.cc/43Th5VXJ/work-1.png', help_text='Default image for projects'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_testimonial_image',
            field=models.URLField(blank=True, default='https://i.postimg.cc/MTr9j4Yn/client1.jpg', help_text='Default image for testimonials'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='experience_subtitle',
            field=models.CharField(default='My Experience', help_text='Experience section subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='experience_title',
            field=models.CharField(default='My Abilities', help_text='Experience section title', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_link',
            field=models.URLField(blank=True, help_text='Footer copyright link URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_link_text',
            field=models.CharField(blank=True, help_text='Footer copyright link text', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_text',
            field=models.CharField(default='All rights reserved', help_text='Footer copyright text', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_subtitle',
            field=models.CharField(default='Recent Works', help_text='Portfolio section subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_title',
            field=models.CharField(default='My Portfolio', help_text='Portfolio section title', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='qualifications_subtitle',
            field=models.CharField(default='Qualifications', help_text='Qualifications section subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='qualifications_title',
            field=models.CharField(default='My Journey', help_text='Qualifications section title', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_subtitle',
            field=models.CharField(default='What I Offer', help_text='Services section subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_title',
            field=models.CharField(default='Services', help_text='Services section title', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_subtitle',
            field=models.CharField(default='Testimonials', help_text='Testimonials section subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_title',
            field=models.CharField(default='My clients say', help_text='Testimonials section title', max_length=200),
        ),
    ]
