# Generated by Django 5.2.6 on 2025-10-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_sitesettings_contact_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('databases', 'Databases'), ('apis', 'APIs & Integration'), ('cloud', 'Cloud (AWS)'), ('infrastructure', 'Infrastructure as Code'), ('cicd', 'CI/CD & Automation'), ('containers', 'Containers & Orchestration'), ('monitoring', 'Monitoring & Logging'), ('security', 'Security & DevSecOps'), ('tools', 'Tools'), ('other', 'Other')], default='frontend', help_text='Skill category', max_length=50),
        ),
    ]
