# Generated by Django 5.2.6 on 2025-10-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pinterest_url',
            field=models.URLField(blank=True, help_text='Pinterest profile URL'),
        ),
    ]
