# Generated by Django 5.2.6 on 2025-10-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sitesettings_pinterest_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='hide_proficiency',
            field=models.BooleanField(default=False, help_text='Hide proficiency percentage on website'),
        ),
    ]
