# Generated by Django 4.2.23 on 2025-10-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_skill_hide_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='pinterest_url',
        ),
    ]
